### ISSUE TITLE
Get measure by clicking on a route

### ISSUE THREAD

**Issue by gubuntu** [blazek/lrs#24] opened 2018-07-07 13:53 UTC
I have a use case where I need to be able to click anywhere along a route and see the distance from the start. i.e. it would be really useful to add an interactive element to the Measures tab.

**Comment by gubuntu** [comment] 2018-07-09 18:35
Ah that's good to know - so the LRS layer has an M dimension? And Identify will interpolate between vertices?

**Comment by blazek** [comment] 2018-07-12 06:35
Yes

**Comment by gubuntu** [comment] 2018-07-12 08:41
I've tested and identify shows only the M value of the nearest vertex, it does not interpolate. So that is useful but not quite as nice as full interpolation. LRS could fill that gap...

**Comment by blazek** [comment] 2018-07-12 09:03
It seems to be regression in QGIS, I have implemented "Closest point M" here https://github.com/qgis/QGIS/commit/5c6e794b2d57e as replacement of the functionality in the LRS  plugin 0.x. Note that it was "Closest point" and now there is "Closes vertex"  in the identify window. No idea who why when changed it. Closest vertex is definitely less useful, but if it is necessary to have also vertex, there should be both closest point and vertex.

Please fill a bug for QGIS.

**Comment by gubuntu** [comment] 2018-07-12 09:59
https://issues.qgis.org/issues/19403

**Comment by blazek** [comment] 2018-08-13 18:47
It is not bug in the plugin but regression in QGIS, I'll keep it open until it is resolved in QGIS.

**Comment by blazek** [comment] 2018-08-14 19:35
It was fixed in QGIS for 3.4.

**Closed by blazek** 2018-08-14 19:35 UTC
